name: "Scrypted Thin"
version: "18-bullseye-thin-v0.6.3"
slug: scrypted-thin
description: "Thin version of Scrypted with smaller image size and some dependencies removed"
url: "https://github.com/koush/scrypted"
arch:
  - aarch64
  - amd64
  - armv7
image: koush/scrypted
host_network: true
environment:
  SCRYPTED_VOLUME: "/data/scrypted_data"
backup_exclude:
  - /server
webui: "https://[HOST]:[PORT:10443]"
stage: experimental
advanced: true
init: false
hassio_role: default
